FROM python:3.11-slim
WORKDIR /app
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r backend/requirements.txt
COPY backend /app
ENV FLASK_APP=app.py
CMD ["gunicorn","-b","0.0.0.0:5000","app:create_app()"]
